### ISSUE TITLE
Rails 5, beta 3: undefined method `encode_big_decimal_as_string='

### ISSUE THREAD

**Issue by parse** [rails/activesupport-json_encoder#7]
Since encode_big_decimal_as_string was deprecated in Rails 5, we now get an error message:

```
/vagrant/config/environment.rb:4:in `<top (required)>': undefined method `encode_big_decimal_as_string=' for ActiveSupport:Module (NoMethodError)
    from /var/lib/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require'
    from /var/lib/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `block in require'
    from /var/lib/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
    from /var/lib/gems/2.2.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require'
    from /vagrant/config.ru:3:in `block in <main>'
    from /home/vagrant/.bundler/ruby/2.2.0/rack-ea2ed578c368/lib/rack/builder.rb:55:in `instance_eval'
    from /home/vagrant/.bundler/ruby/2.2.0/rack-ea2ed578c368/lib/rack/builder.rb:55:in `initialize'
```

Code:

```
ActiveSupport.encode_big_decimal_as_string = false
```

**Comment by rafaelfranca** [comment]
This gem doesn't support Rails 5
